create database dbOdonto;
use dbOdonto;

----- CREATE TABLE ----------------------

CREATE TABLE PACIENTE (
	ID INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	EMAIL VARCHAR(70) NOT NULL,
	ENDERECO VARCHAR(120) NOT NULL,
	CELULAR VARCHAR(14) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	CHECK (SEXO = 'M' OR 'F'),
	CONSTRAINT PRIMARY KEY (ID)
);

CREATE TABLE DENTISTA (
	ID INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	CPF VARCHAR(14) NOT NULL,
	EMAIL VARCHAR(70) NOT NULL,
	CELULAR VARCHAR(14) NOT NULL,
	ESPECIALIDADE VARCHAR(100),
	CONSTRAINT PRIMARY KEY (ID)
);

CREATE TABLE PROCEDIMENTO (
	ID INT NOT NULL AUTO_INCREMENT,
	DESCRICAO VARCHAR(200) NOT NULL,
	VALOR DOUBLE NOT NULL,
	CONSTRAINT PRIMARY KEY (ID)
);

CREATE TABLE CONSULTA (
	ID INT NOT NULL AUTO_INCREMENT,
	DATA_CONSULTA DATE NOT NULL,
	HORA_CONSULTA TIME NOT NULL,
	VALOR_CONSULTA DOUBLE NOT NULL,
	ATIVO BOOL,
	OBS VARCHAR(200),
	ID_PACIENTE INT NOT NULL,
	ID_DENTISTA INT NOT NULL,
	CONSTRAINT FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID) ON DELETE CASCADE,
	CONSTRAINT FOREIGN KEY (ID_DENTISTA) REFERENCES DENTISTA(ID) ON DELETE CASCADE,
	CONSTRAINT PRIMARY KEY (ID)
);

CREATE TABLE CONSULTA_PROCEDIMENTO (
	ID INT NOT NULL AUTO_INCREMENT,
	ID_CONSULTA INT NOT NULL,
	ID_PROCEDIMENTO INT NOT NULL,
	CONSTRAINT FOREIGN KEY (ID_CONSULTA) REFERENCES CONSULTA(ID) ON DELETE CASCADE,
	CONSTRAINT FOREIGN KEY (ID_PROCEDIMENTO) REFERENCES PROCEDIMENTO(ID) ON DELETE CASCADE,
	CONSTRAINT PRIMARY KEY (ID)
);

------- INSERTS ---------------------------------------
INSERT INTO dbOdonto.DENTISTA
(NOME, CPF, EMAIL, CELULAR, ESPECIALIDADE)
VALUES('Victor Zenezi', '11111111111', 'fu@email.com', '912341234', 'Odontopediatria');
INSERT INTO dbOdonto.DENTISTA
(NOME, CPF, EMAIL, CELULAR, ESPECIALIDADE)
VALUES('Fulano', '11111111111', 'fu@email.com', '912341234', 'Radiologia Odontológica');
INSERT INTO dbOdonto.DENTISTA
(NOME, CPF, EMAIL, CELULAR, ESPECIALIDADE)
VALUES('Lucas', '11111111111', 'lucas@mail.com', '912341234', 'Clareamento');

INSERT INTO dbOdonto.PROCEDIMENTO
(DESCRICAO, VALOR)
VALUES('Canal', 1000);
INSERT INTO dbOdonto.PROCEDIMENTO
(DESCRICAO, VALOR)
VALUES('Clareamento', 1000);


INSERT INTO dbOdonto.CONSULTA_PROCEDIMENTO
(ID_CONSULTA, ID_PROCEDIMENTO)
VALUES(5, 1);
